apiVersion: v1
kind: ResourceQuota
metadata:
  name: comp-qutota
  namespace: dev
spec:
  hard:
    pods: "5"
    requests.cpu: "2"
    requests.memory: "2Gi"
    limits.cpu: "10"
    limits.memory: "4Gi"

