apiVersion: v1
kind: ReplicationController
metadata:
   name: mypod
   labels:
     app: javaapp
     type: frontend
spec:
  template:       
    metadata:
      name: tomcat
      labels:
        app: tomcat
        type: frontend
    spec:
      containers:
      - name: tomcat
        image: tomcat
  replicas: 2

